---
# title: "Acronyms/Abbreviations"
title: Abbreviations and acronyms used in the workshop
format:
    html: default
---

```{r list_acronyms, echo=FALSE}
#
# Add a new acronym here anywhere in the following list by following the syntax
#
acronyms <- c(
# Syntax:
#
# "ACRONYM" = "ACRONYM MEANING HERE", <- Don't forget the comma ; )
#
  "ENVO" = "Environmental Ontology",
  "EMBL" = "European Molecular Biology Laboratory",
  "EMBL-EBI" = "EMBL's European Bioinformatics Institute",
  "NCBO" = "National (USA) Center for Biomedical Ontology",
  "OLS" = "Ontology Lookup Service",
  "OBO" = "Open Biology and Biomedical Ontology",
  "NMDC" = "National (USA) Microbiome Data Collaborative",
  "MIxS" = "Minimal Information about any (x) Sequences",
  "FAIR" = "Findable, Accessible, Interoperable and Reusable",
  "NFDI" = "National (DE) Research Data Infrastructure"
)
```

```{r display_acronyms, echo=FALSE,results='asis'}
library(magrittr, quietly = TRUE)
tbl <- acronyms %>% 
  tibble::enframe(name = "Acronym", value = "Definition") %>% 
  dplyr::arrange(Acronym) %>%
  knitr::kable(format = "pipe")
cat(tbl, "\n: {.striped .hover .fs-4}", sep = "\n")
```


*Missing an acronym?* This might benefit others, so please [fill an issue on our Gitlab](https://git.rwth-aachen.de/clavellab/workshop-biometadata-01/-/issues/new?issuable_template=new_acronym), we will add it soon!
