# .github/workflows/mirror.yml
name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '47 11 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: kaidokert/github-mirror-action@v4
        with:
          origin: 'https://git.rwth-aachen.de/clavellab/workshop-biometadata-01'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
